# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from vlp_fir/send_msgs.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class send_msgs(genpy.Message):
  _md5sum = "bf460c9b2194df7c3ccef2b14e93b960"
  _type = "vlp_fir/send_msgs"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool date
int32 num
float64 x
float64 y
float64 z
float64 len
float64 width
float64 height
"""
  __slots__ = ['date','num','x','y','z','len','width','height']
  _slot_types = ['bool','int32','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       date,num,x,y,z,len,width,height

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(send_msgs, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.date is None:
        self.date = False
      if self.num is None:
        self.num = 0
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
      if self.len is None:
        self.len = 0.
      if self.width is None:
        self.width = 0.
      if self.height is None:
        self.height = 0.
    else:
      self.date = False
      self.num = 0
      self.x = 0.
      self.y = 0.
      self.z = 0.
      self.len = 0.
      self.width = 0.
      self.height = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_Bi6d().pack(_x.date, _x.num, _x.x, _x.y, _x.z, _x.len, _x.width, _x.height))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 53
      (_x.date, _x.num, _x.x, _x.y, _x.z, _x.len, _x.width, _x.height,) = _get_struct_Bi6d().unpack(str[start:end])
      self.date = bool(self.date)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_Bi6d().pack(_x.date, _x.num, _x.x, _x.y, _x.z, _x.len, _x.width, _x.height))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 53
      (_x.date, _x.num, _x.x, _x.y, _x.z, _x.len, _x.width, _x.height,) = _get_struct_Bi6d().unpack(str[start:end])
      self.date = bool(self.date)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_Bi6d = None
def _get_struct_Bi6d():
    global _struct_Bi6d
    if _struct_Bi6d is None:
        _struct_Bi6d = struct.Struct("<Bi6d")
    return _struct_Bi6d
