<?xml version="1.0"?>
<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="length" value="1.080" /> 
    <xacro:property name="width" value="0.4" /> 
    <xacro:property name="height" value="0.336" /> 
    <xacro:property name="mass" value="48" />
    <xacro:property name="ground" value="0.135" />
    <xacro:property name="wheelrad" value="0.18" />   
    <xacro:property name="wheelwid" value="0.10" />
    <xacro:property name="wheeldis" value="0.65" />
    <xacro:property name="wheelseperate" value="0.576" />
    <xacro:property name="wheelmass" value="1" />

    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.001 0.001 0.001"/>
            </geometry>
        </visual>
    </link>

    <joint name="base_joint" type="fixed">
        <origin xyz="0 0 ${height/2+ground}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="chasis"/>
    </joint>

    <link name="chasis">
        <visual>
            <origin xyz="0 0 0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${length} ${width} ${height}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${length} ${width} ${height}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0.0 0.0 0.0"/>
            <mass value="${mass}"/>
            <inertia
            ixx="${mass / 12.0 * (width*width + height*height)}" ixy="0.0" ixz="0.0"
            iyy="${mass / 12.0 * (height*height + width*width)}" iyz="0.0"
            izz="${mass / 12.0 * (width*width + width*width)}"/>
        </inertial>
    </link>

    <joint name="left_front_joint" type="continuous">
        <parent link="chasis"/>
        <child link="left_front_wheel"/>
        <origin xyz="${wheeldis/2} ${wheelseperate/2} ${-(height/2+ground-wheelrad)}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <dynamics damping="0.5"/>
      </joint>

    <link name="left_front_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="1.5707 0 0"/>
            <geometry>
                <cylinder radius="${wheelrad}" length="${wheelwid}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="1.5707 0 0"/>
            <geometry>
                <cylinder radius="${wheelrad}" length="${wheelwid}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="1.5707 0 0"/>
            <mass value="${wheelmass}"/>
            <inertia
            ixx="${wheelmass / 12.0 * (3*wheelrad*wheelrad + wheelwid)}" ixy="0.0" ixz="0.0"
            iyy="${ (wheelmass * wheelrad * wheelrad) / 2}" iyz="0.0"
            izz="${wheelmass / 12.0 * (3*wheelrad*wheelrad + wheelwid)}"/>
            </inertial>
    </link>

    <joint name="left_rear_joint" type="continuous">
        <parent link="chasis"/>
        <child link="left_rear_wheel"/>
        <origin xyz="${-wheeldis/2} ${wheelseperate/2} ${-(height/2+ground-wheelrad)}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <dynamics damping="0.5"/>
      </joint>

    <link name="left_rear_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="1.5707 0 0"/>
            <geometry>
                <cylinder radius="${wheelrad}" length="${wheelwid}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="1.5707 0 0"/>
            <geometry>
                <cylinder radius="${wheelrad}" length="${wheelwid}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="1.5707 0 0"/>
            <mass value="${wheelmass}"/>
            <inertia
            ixx="${wheelmass / 12.0 * (3*wheelrad*wheelrad + wheelwid)}" ixy="0.0" ixz="0.0"
            iyy="${ (wheelmass * wheelrad * wheelrad) / 2}" iyz="0.0"
            izz="${wheelmass / 12.0 * (3*wheelrad*wheelrad + wheelwid)}"/>
            </inertial>
    </link>

    <joint name="right_rear_joint" type="continuous">
        <parent link="chasis"/>
        <child link="right_rear_wheel"/>
        <origin xyz="${-wheeldis/2} ${-wheelseperate/2} ${-(height/2+ground-wheelrad)}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <dynamics damping="0.5"/>
      </joint>

    <link name="right_rear_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="1.5707 0 0"/>
            <geometry>
                <cylinder radius="${wheelrad}" length="${wheelwid}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="1.5707 0 0"/>
            <geometry>
                <cylinder radius="${wheelrad}" length="${wheelwid}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="1.5707 0 0"/>
            <mass value="${wheelmass}"/>
            <inertia
            ixx="${wheelmass / 12.0 * (3*wheelrad*wheelrad + wheelwid)}" ixy="0.0" ixz="0.0"
            iyy="${ (wheelmass * wheelrad * wheelrad) / 2}" iyz="0.0"
            izz="${wheelmass / 12.0 * (3*wheelrad*wheelrad + wheelwid)}"/>
            </inertial>
    </link>

    <joint name="right_front_joint" type="continuous">
        <parent link="chasis"/>
        <child link="right_front_wheel"/>
        <origin xyz="${wheeldis/2} ${-wheelseperate/2} ${-(height/2+ground-wheelrad)}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <dynamics damping="0.5"/>
      </joint>

    <link name="right_front_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="1.5707 0 0"/>
            <geometry>
                <cylinder radius="${wheelrad}" length="${wheelwid}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="1.5707 0 0"/>
            <geometry>
                <cylinder radius="${wheelrad}" length="${wheelwid}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="1.5707 0 0"/>
            <mass value="${wheelmass}"/>
            <inertia
            ixx="${wheelmass / 12.0 * (3*wheelrad*wheelrad + wheelwid)}" ixy="0.0" ixz="0.0"
            iyy="${ (wheelmass * wheelrad * wheelrad) / 2}" iyz="0.0"
            izz="${wheelmass / 12.0 * (3*wheelrad*wheelrad + wheelwid)}"/>
            </inertial>
    </link>
    
    <link name="lidar">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.1" length="0.05"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.1" length="0.05"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0.1"/>
            <inertia
            ixx="${0.1 / 12.0 * (3*0.1*0.1 + 0.05)}" ixy="0.0" ixz="0.0"
            iyy="${ (0.1 * 0.1 * 0.1) / 2}" iyz="0.0"
            izz="${0.1 / 12.0 * (3*0.1*0.1 + 0.05)}"/>
            </inertial>
    </link>
    
    <joint name="lidarfix" type="fixed">
        <origin xyz="0 0 0.6" rpy="0 0 0"/>
        <parent link="chasis"/>
        <child link="lidar"/>
      </joint>
    
    <gazebo>
        <plugin name="object_controller" filename="libgazebo_ros_planar_move.so">
            <commandTopic>cmd_vel</commandTopic>
            <odometryTopic>odom</odometryTopic>
            <odometryFrame>odom</odometryFrame>
            <odometryRate>20.0</odometryRate>
            <robotBaseFrame>base_link</robotBaseFrame>
        </plugin>   
    </gazebo>

    <gazebo reference="lidar">
        <sensor type="ray" name="VLP16">
          <pose>0 0 0 0 0 0</pose>
          <visualize>false</visualize>
          <update_rate>10</update_rate>
          <ray>
            <scan>
              <horizontal>
                <samples>440</samples>
                <resolution>1</resolution>
                <min_angle>-${PI}</min_angle>
                <max_angle>${PI}</max_angle>
              </horizontal>
              <vertical>
                <samples>16</samples>
                <resolution>1</resolution>
                <min_angle>-${15.0*PI/180.0}</min_angle>
                <max_angle> ${15.0*PI/180.0}</max_angle>
              </vertical>
            </scan>
            <range>
              <min>0.3</min>
              <max>131</max>
              <resolution>0.001</resolution>
            </range>
            <noise>
              <type>gaussian</type>
              <mean>0.0</mean>
              <stddev>0.0</stddev>
            </noise>
          </ray>
          <plugin name="gazebo_ros_laser_controller" filename="libgazebo_ros_velodyne_laser.so">
            <topicName>livox/lidar</topicName>
            <frameName>lidar</frameName>
            <min_range>0.9</min_range>
            <max_range>130</max_range>
            <gaussianNoise>0.08</gaussianNoise>
            <always_on>true</always_on>
          </plugin>
        </sensor>
    </gazebo>

    <!-- <gazebo>  
        <plugin name="gps" filename="libhector_gazebo_ros_gps.so">  
            <updateRate>20.0</updateRate>  
            <topicName>gpsinfo</topicName>  
            <gaussianNoise>0.0 0.0 0.0</gaussianNoise>  
            <offset>0 0 0</offset>  
            <velocityGaussianNoise>0 0 0</velocityGaussianNoise>  
            <frameId>base_link</frameId>  
        </plugin>  
    </gazebo>   -->

</robot>
