// Generated by gencpp from file scout/RL_input_msgs.msg
// DO NOT EDIT!


#ifndef SCOUT_MESSAGE_RL_INPUT_MSGS_H
#define SCOUT_MESSAGE_RL_INPUT_MSGS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace scout
{
template <class ContainerAllocator>
struct RL_input_msgs_
{
  typedef RL_input_msgs_<ContainerAllocator> Type;

  RL_input_msgs_()
    : header()
    , me_x(0.0)
    , me_y(0.0)
    , me_yaw(0.0)
    , me_v(0.0)
    , me_w(0.0)  {
    }
  RL_input_msgs_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , me_x(0.0)
    , me_y(0.0)
    , me_yaw(0.0)
    , me_v(0.0)
    , me_w(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _me_x_type;
  _me_x_type me_x;

   typedef double _me_y_type;
  _me_y_type me_y;

   typedef double _me_yaw_type;
  _me_yaw_type me_yaw;

   typedef double _me_v_type;
  _me_v_type me_v;

   typedef double _me_w_type;
  _me_w_type me_w;





  typedef boost::shared_ptr< ::scout::RL_input_msgs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scout::RL_input_msgs_<ContainerAllocator> const> ConstPtr;

}; // struct RL_input_msgs_

typedef ::scout::RL_input_msgs_<std::allocator<void> > RL_input_msgs;

typedef boost::shared_ptr< ::scout::RL_input_msgs > RL_input_msgsPtr;
typedef boost::shared_ptr< ::scout::RL_input_msgs const> RL_input_msgsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scout::RL_input_msgs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scout::RL_input_msgs_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace scout

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'scout': ['/home/xyw/BUAA/Graduation/src/scout/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::scout::RL_input_msgs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scout::RL_input_msgs_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scout::RL_input_msgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scout::RL_input_msgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scout::RL_input_msgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scout::RL_input_msgs_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scout::RL_input_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f2ea7f125f21cbef73d64dd7a90ab98";
  }

  static const char* value(const ::scout::RL_input_msgs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f2ea7f125f21cbeULL;
  static const uint64_t static_value2 = 0xf73d64dd7a90ab98ULL;
};

template<class ContainerAllocator>
struct DataType< ::scout::RL_input_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scout/RL_input_msgs";
  }

  static const char* value(const ::scout::RL_input_msgs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scout::RL_input_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64 me_x\n\
float64 me_y\n\
float64 me_yaw\n\
float64 me_v\n\
float64 me_w\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::scout::RL_input_msgs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scout::RL_input_msgs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.me_x);
      stream.next(m.me_y);
      stream.next(m.me_yaw);
      stream.next(m.me_v);
      stream.next(m.me_w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RL_input_msgs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scout::RL_input_msgs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scout::RL_input_msgs_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "me_x: ";
    Printer<double>::stream(s, indent + "  ", v.me_x);
    s << indent << "me_y: ";
    Printer<double>::stream(s, indent + "  ", v.me_y);
    s << indent << "me_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.me_yaw);
    s << indent << "me_v: ";
    Printer<double>::stream(s, indent + "  ", v.me_v);
    s << indent << "me_w: ";
    Printer<double>::stream(s, indent + "  ", v.me_w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCOUT_MESSAGE_RL_INPUT_MSGS_H
